export const FETCH_SUCCESSFUL_TODAY = 'FETCH_SUCCESSFUL_TODAY';
export const FETCH_PENDING_TODAY = 'FETCH_PENDING_TODAY';
export const FETCH_ERROR_TODAY = 'FETCH_ERROR_TODAY';

export const FETCH_SUCCESSFUL_TOMORROW = 'FETCH_SUCCESSFUL_TOMORROW';
export const FETCH_PENDING_TOMORROW = 'FETCH_PENDING_TOMORROW';
export const FETCH_ERROR_TOMORROW = 'FETCH_ERROR_TOMORROW';

export const FETCH_SUCCESSFUL_FUTURE = 'FETCH_SUCCESSFUL_FUTURE';
export const FETCH_PENDING_FUTURE = 'FETCH_PENDING_FUTURE';
export const FETCH_ERROR_FUTURE = 'FETCH_ERROR_FUTURE';

